name = "rodeo-data-api"
main = "src/index.ts"
compatibility_date = "2026-05-13"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
CACHE_TTL_SECONDS = "300"
CACHE_VERSION = "2026-07-31-1"
RODEOS_CACHE_TTL_SECONDS = "1800"
SCHEMA_CACHE_TTL_SECONDS = "3600"
CACHE_STALE_WHILE_REVALIDATE_SECONDS = "600"
